# wdocker vars:

#wd# docker = docker
#wd# name = many_commands

# wdocker commands:

#wd# build: {docker} build -t {name} .
#wd# run: {docker} run -it --name {name} {name}
#wd# shell: {docker} exec -it {name} bash
#wd# start: {docker} start {name}
#wd# stop: {docker} stop {name}
#wd# attach: clear ;; {docker} attach {name}

FROM debian:latest
CMD watch ps aux
