# wdocker vars:

#wd# docker = docker
#wd# name = combined
#wd# build = {docker} build -t {name} .
#wd# run = {docker} run -it --name {name} {name}

# wdocker commands:

#wd# build: {build}
#wd# run: {run}
#wd# up: {build} && {run}

FROM debian:latest
CMD watch ps aux
